### ISSUE TITLE
Duplicate class a.a found in modules XXX

### ISSUE THREAD

**Issue by cookseym** [socure-inc/socure-docv-sdk-android#6]
I am integrating Socure-DocV v 3.0.0 and upon compiling, I am getting the following error message with a class duplicate conflict with another SDK.

```
Execution failed for task ':app:checkAlphaDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class a.a found in modules jetified-XXX-XXX
```   

Can this SDK be generated with a "flat" package hierarchy using the proguard flags
`repackageclasses or flattenpackagehierarchy` ?

**Comment by ItayFeld** [comment]
Also facing same duplicate classes error because of classes that were added manually to this project from the opencv-contours dependency which I use for another reason besides DocV
Files - 
org.opencv.android.Utils
org.opencv.core.Core
org.opencv.core.Mat
org.opencv.core.Range
org.opencv.imgproc.Imgproc

**Comment by MarkyL** [comment]
I'm facing the same issue, any help here?

**Comment by cookseym** [comment]
@ItayFeld & & @MarkyL Can you try this?

https://docs.gradle.org/current/userguide/resolution_rules.html#sec:disabling_resolution_transitive_dependencies

The fact that the classes you are seeing issues with are not obfuscated lead me to believe you should be able to configure your project to get around this.

As for me, I still have the issue if I use the older version of the other dependency, but, they updated their code and flattened it like I suggested and it now plays nicely with this one.  However, this will continue to be an issue for others unless Socure fixes this.

**Comment by buraksocure** [comment]
Thank you @MarkyL @ItayFeld @cookseym for reporting this. 

Our team acknowledged the issue and currently working on to fix it, 

We will let you know once we have a fix in place.

**Comment by buraksocure** [comment]
Happy to inform that the issue related OpenCV has been resolved. Please use this version -> https://github.com/socure-inc/socure-docv-sdk-android/releases/tag/3.0.2
